# Generated by Django 4.2.20 on 2025-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('all', 'All'), ('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed')]),
        ),
    ]
